version: "3.8"

services:
  app:
    image: todo-frontend-dev
    container_name: todo-frontend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
